'use strict';

// WHAT ONE ASSISTANT COSTS THIS COMPUTER IN MEMORY.
//
// THE INCIDENT THIS SUITE IS WRITTEN AGAINST. On 2026-09-03 the owner's app
// resumed nine assistants between 21:15:50 and 21:24:31 local and died at
// 21:26:20 with the CPU pegged. Two of one assistant's MCP servers had already
// aborted at 21:11:56 inside V8::FatalProcessOutOfMemory during concurrent
// Maglev compilation (crash-dumps 76bc6b89 / a11262c6, both process type
// `node`, both created in the same second).
//
// MEASURED, not estimated, and the numbers are in
// REPORT-crash-20260903/evidence/C/:
//
//   heapcap-probe.txt      an ELECTRON_RUN_AS_NODE child of this build's
//                          electron.exe gets heap_size_limit = 4192 MB with no
//                          cap; 608 MB at --max-old-space-size=512; 408 MB at
//                          384. The variable IS honoured.
//   measure-toolsenabled.json / measure-toolsenabled-readonly.json
//                          each server's real steady state: 30-60 MB private
//                          bytes idle and after twenty tool calls.
//
// So the generated document was starting servers with a FOUR GIGABYTE V8
// ceiling apiece against a 30-60 MB working size, three per assistant, on a
// 32 GB machine whose commit limit is 34.7 GB. Nine assistants is a 113 GB
// ceiling. Nothing bounded a runaway, so the machine ran out instead of the
// server.
//
// WHAT IS PROVED HERE. Two properties of the document generateMcpConfig()
// writes, at the level of the generated bytes: every server it starts carries a
// heap ceiling, and an assistant that was not given browser tools does not get
// the browser process at all. Neither claim needs a spawned child, which is why
// they can be asserted in a targeted suite on a shared four-core machine.
//
// WHAT IS NOT PROVED HERE. That a capped server ACTUALLY aborts at its ceiling
// -- that is a property of V8, established by the probe above rather than by
// re-running an out-of-memory in the test suite.

const isolated = require('./lib/isolated-environment').activate('mcp-server-footprint');
const test = require('node:test');
const assert = require('node:assert/strict');
const os = require('node:os');
const path = require('node:path');

const machineRecord = require('../src/lib/setup/machine-record');

void isolated;

const REPO_ROOT = path.resolve(__dirname, '..');

function recordFor(tier) {
  return machineRecord.buildMachineRecord({
    tier,
    installRoot: REPO_ROOT,
    servicesRoot: path.join(os.tmpdir(), 'mcp-server-footprint-services'),
    nodePath: process.execPath,
    workspaceRoots: [path.join(os.tmpdir(), 'mcp-server-footprint-workspace')]
  });
}

// The catalogue's own numbers, read rather than restated: a test that hardcoded
// 512 would pass while the product shipped 4096, which is the failure it exists
// to catch.
function catalogueCap(name) {
  const entry = machineRecord.SERVER_CATALOGUE.find(server => server.name === name);
  assert.ok(entry, `the catalogue no longer contains a server named ${name}`);
  return entry.heapCapMB;
}

test('every generated MCP server carries a V8 heap ceiling', () => {
  const { document } = machineRecord.generateMcpConfig(recordFor('unrestricted'));
  const names = Object.keys(document.mcpServers);
  assert.ok(names.length >= 2, 'the unrestricted level generates more than one server');
  for (const name of names) {
    const entry = document.mcpServers[name];
    assert.ok(entry.env && typeof entry.env.NODE_OPTIONS === 'string',
      `${name} was generated with no NODE_OPTIONS, so its heap is the 4192 MB default`);
    assert.match(entry.env.NODE_OPTIONS, /--max-old-space-size=\d+/,
      `${name}'s NODE_OPTIONS does not bound old space`);
    const megabytes = Number(/--max-old-space-size=(\d+)/.exec(entry.env.NODE_OPTIONS)[1]);
    assert.equal(megabytes, catalogueCap(name));
    // Against the MEASURED steady state (30-60 MB private): a ceiling above one
    // gigabyte per server is not a ceiling on a 32 GB machine running nine
    // assistants at three servers apiece.
    assert.ok(megabytes <= 1024, `${name} may take ${megabytes} MB of old space, which is not a bound`);
  }
});

test('the read-only server is given a smaller ceiling than the write-capable one', () => {
  // Both run for the SAME assistant at standard and unrestricted. The read-only
  // copy advertises 95 tools against 240 (measured, evidence/C/measure-*.json)
  // and can never write, so it must not cost as much as the full one.
  assert.ok(catalogueCap('toolsenabled-readonly') < catalogueCap('toolsenabled'));
});

test('an assistant started without browser tools gets no browser process', () => {
  const record = recordFor('unrestricted');
  const withBrowser = machineRecord.generateMcpConfig(record, { browserTools: true });
  const withoutBrowser = machineRecord.generateMcpConfig(record, { browserTools: false });

  assert.ok(Object.hasOwn(withBrowser.document.mcpServers, 'playwright'),
    'the default is unchanged: an installed machine still gets its browser server');
  assert.equal(Object.hasOwn(withoutBrowser.document.mcpServers, 'playwright'), false,
    'the browser server is still in the document, so the process is still started');

  // The omission is RECORDED, so a caller can tell "we chose not to" apart from
  // "the file was missing".
  const skipped = withoutBrowser.skipped.find(entry => entry.name === 'playwright');
  assert.ok(skipped, 'the omitted browser server was not reported to the caller');
  assert.match(skipped.reason, /browser tools/);

  // Everything else is untouched: this is one process fewer, not a narrower
  // tool surface.
  assert.deepEqual(
    Object.keys(withoutBrowser.document.mcpServers),
    Object.keys(withBrowser.document.mcpServers).filter(name => name !== 'playwright')
  );
});

test('the default is byte-identical to what the installer has always written, apart from the ceiling', () => {
  const record = recordFor('unrestricted');
  const stated = machineRecord.generateMcpConfig(record, { browserTools: true });
  const omitted = machineRecord.generateMcpConfig(record);
  assert.deepEqual(omitted.document, stated.document);
});

test('a server that does not say what it may cost refuses to be generated', () => {
  // The catalogue is frozen, so the refusal is proved through the exported
  // asserter on a copy rather than by mutating the product's own list.
  const catalogue = machineRecord.SERVER_CATALOGUE.map(server => ({ ...server }));
  delete catalogue[0].heapCapMB;
  assert.throws(
    () => machineRecord.assertServerCatalogue(catalogue),
    error => error.code === 'SETUP_SERVER_CATALOGUE_INVALID' && /how much memory/.test(error.message)
  );
});

test('whether an assistant gets browser tools has to be stated, not guessed', () => {
  assert.throws(
    () => machineRecord.generateMcpConfig(recordFor('unrestricted'), { browserTools: 'yes' }),
    error => error.code === 'SETUP_BROWSER_TOOLS_INVALID'
  );
});

// --- who the third process is actually generated for -------------------------
//
// The catalogue option above is only half the change: something has to decide.
// prepareClaudeToolSurface() generates ONE document per assistant, so it is the
// place where "this assistant will never open a page" can be known.
//
// MEASURED 2026-09-03, three consecutive runs of exactly the command the
// generated document spells (evidence/C/playwright-gateway-lifetime.txt): with
// no ToolsEnabled-owned browser running, src/playwright-gateway.js exits 2
// after 835-1170 ms with "The ToolsEnabled-owned browser could not be
// revalidated". It answers no call. So on a machine where nobody has run
// browser.start, that process is a start cost and a failed server in the
// client's log and nothing else -- once per assistant, nine times over on the
// evening this suite is written about.

const fs = require('node:fs');
const confinement = require('../src/lib/agent-session-confinement');

const scratchDirectories = [];
function scratchRoot(prefix) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), `mcp-footprint-${prefix}-`));
  scratchDirectories.push(directory);
  // %TEMP% is an 8.3 short name on this machine and the confinement boundary
  // answers the long one; expand once so every path below is a location rather
  // than a spelling.
  try { return fs.realpathSync.native(directory); } catch { return directory; }
}
test.after(() => {
  for (const directory of scratchDirectories) {
    try { fs.rmSync(directory, { recursive: true, force: true }); } catch { /* a leftover temp dir is not a failure */ }
  }
});

// The generator is INJECTED, so these cases assert what the surface asks for
// rather than re-deriving a whole document.
function browserToolsAskedFor(options) {
  const servicesRoot = scratchRoot('services');
  const record = machineRecord.buildMachineRecord({
    tier: 'standard',
    installRoot: REPO_ROOT,
    servicesRoot,
    nodePath: process.execPath,
    workspaceRoots: [scratchRoot('workspace')]
  });
  machineRecord.writeMachineRecord(record, { servicesRoot });
  let asked;
  confinement.prepareClaudeToolSurface(confinement.agentConfinement('standard'), {
    record,
    servicesRoot,
    ...options,
    generate: (_record, generatorOptions) => {
      asked = generatorOptions.browserTools;
      return machineRecord.generateMcpConfig(_record, generatorOptions);
    }
  });
  return asked;
}

test("the person's own session keeps its browser server", () => {
  assert.equal(browserToolsAskedFor({}), true);
});

test('a declared agent circle is generated without the browser process', () => {
  assert.equal(browserToolsAskedFor({ agentId: 'manager-1' }), false);
});

test('a caller that knows this circle has browser work says so and gets it', () => {
  assert.equal(browserToolsAskedFor({ agentId: 'manager-1', browserTools: true }), true);
  // And the same statement can take it away from the person's own session,
  // which is the seam the application needs to offer the choice at all.
  assert.equal(browserToolsAskedFor({ browserTools: false }), false);
});

test('an unreadable browser-work statement is refused rather than guessed', () => {
  assert.throws(
    () => browserToolsAskedFor({ browserTools: 'maybe' }),
    error => error.code === 'AGENT_CONFINEMENT_BROWSER_TOOLS_INVALID'
  );
});
