'use strict';

const VCS_ERROR_CODES = Object.freeze({
  NOT_IMPLEMENTED: 'VCS_NOT_IMPLEMENTED',
  CONTRACT_VIOLATION: 'VCS_CONTRACT_VIOLATION',
  UNKNOWN: 'VCS_UNKNOWN',
  INCOMPLETE_ARTIFACT: 'VCS_INCOMPLETE_ARTIFACT',
  POLICY_UNRESOLVED: 'VCS_POLICY_UNRESOLVED',
  UNAUTHORIZED: 'VCS_UNAUTHORIZED',
  LEASE_CONFLICT: 'VCS_LEASE_CONFLICT',
  CLAIM_EXPIRED: 'VCS_CLAIM_EXPIRED',
  CLAIM_REVOKED: 'VCS_CLAIM_REVOKED',
  CLAIM_SCOPE_UNKNOWN: 'VCS_CLAIM_SCOPE_UNKNOWN',
  CLAIM_OVERLAP_UNRESOLVED: 'VCS_CLAIM_OVERLAP_UNRESOLVED',
  FENCE_STALE: 'VCS_FENCE_STALE',
  PROPOSAL_QUARANTINED: 'VCS_PROPOSAL_QUARANTINED',
  SNAPSHOT_STALE: 'VCS_SNAPSHOT_STALE',
  PROOF_STALE: 'VCS_PROOF_STALE',
  POLICY_STALE: 'VCS_POLICY_STALE',
  RECEIPT_STALE: 'VCS_RECEIPT_STALE',
  RECEIPT_EXPIRED: 'VCS_RECEIPT_EXPIRED',
  CONFLICT_UNRESOLVED: 'VCS_CONFLICT_UNRESOLVED',
  CONFLICT_SEMANTIC: 'VCS_CONFLICT_SEMANTIC',
  TRANSACTION_PRECONDITION: 'VCS_TXN_PRECONDITION',
  TRANSACTION_IN_DOUBT: 'VCS_TXN_IN_DOUBT',
  PARTICIPANT_IN_DOUBT: 'VCS_PARTICIPANT_IN_DOUBT',
  DESTINATION_UNPROVEN: 'VCS_DESTINATION_UNPROVEN',
  CLEANUP_REFUSED: 'VCS_CLEANUP_REFUSED',
  CONSUMER_DRIFT: 'VCS_CONSUMER_DRIFT',
  RECOVERY_UNAVAILABLE: 'VCS_RECOVERY_UNAVAILABLE',
  INTEGRITY_FAILURE: 'VCS_INTEGRITY_FAILURE',
  BACKUP_INCOMPLETE: 'VCS_BACKUP_INCOMPLETE',
  RESTORE_UNPROVEN: 'VCS_RESTORE_UNPROVEN',
  ADAPTER_UNAVAILABLE: 'VCS_ADAPTER_UNAVAILABLE',
  GIT_COMPATIBILITY: 'VCS_GIT_COMPATIBILITY',
  IMMUTABLE_RECORD: 'VCS_IMMUTABLE_RECORD',
});

class VcsError extends Error {
  /**
   * @param {string} code
   * @param {string} message
   * @param {object} [details]
   * @param {string[]} [safeNextActions]
   */
  constructor(code, message, details = {}, safeNextActions = []) {
    super(message);
    this.name = 'VcsError';
    this.code = code;
    this.details = Object.freeze({ ...details });
    this.safeNextActions = Object.freeze([...safeNextActions]);
  }
}

module.exports = Object.freeze({ VcsError, VCS_ERROR_CODES });
