'use strict';

const CLOUD_ERROR_CODES = Object.freeze({
  UNSAFE_PATH: 'CLOUD_UNSAFE_PATH',
  UNSAFE_MODE: 'CLOUD_UNSAFE_MODE',
  DUPLICATE_PATH: 'CLOUD_DUPLICATE_PATH',
  ALLOWLIST_VIOLATION: 'CLOUD_ALLOWLIST_VIOLATION',
  SIZE_BUDGET_EXCEEDED: 'CLOUD_SIZE_BUDGET_EXCEEDED',
  ACCESS_EVIDENCE_UNSAFE: 'CLOUD_ACCESS_EVIDENCE_UNSAFE',
  PROOF_UNKNOWN: 'CLOUD_PROOF_UNKNOWN',
  BLOB_HASH_MISMATCH: 'CLOUD_BLOB_HASH_MISMATCH',
  BLOB_CONTENT_MISSING: 'CLOUD_BLOB_CONTENT_MISSING',
  SOURCE_DRIFT: 'CLOUD_SOURCE_DRIFT',
  MODEL_MISMATCH: 'CLOUD_MODEL_MISMATCH',
  TERMINAL_CONFLICT: 'CLOUD_TERMINAL_CONFLICT',
  RECONCILIATION_REQUIRED: 'CLOUD_UNKNOWN_RECONCILIATION_REQUIRED',
  NOTHING_TO_RECOVER: 'CLOUD_NOTHING_TO_RECOVER',
  PROVIDER_NOT_ALLOWED: 'CLOUD_PROVIDER_NOT_ALLOWED',
  ENVIRONMENT_NOT_ALLOWED: 'CLOUD_ENVIRONMENT_NOT_ALLOWED',
});

// Regular file modes only: normal (100644) and executable (100755). Symlinks
// (120000), gitlinks/submodules (160000), and trees (040000) are refused as unsafe.
const ALLOWED_FILE_MODES = Object.freeze(['100644', '100755']);

const FILE_MANIFEST_SCHEMA = 'internal-vcs.cloud.file-manifest/v1';
const OUTBOUND_PROOF_SCHEMA = 'internal-vcs.cloud.outbound-proof/v1';

module.exports = Object.freeze({
  CLOUD_ERROR_CODES,
  ALLOWED_FILE_MODES,
  FILE_MANIFEST_SCHEMA,
  OUTBOUND_PROOF_SCHEMA,
});
