// Generated by tools/generate-agent-activity-contracts.js. Do not edit.

export type SchemaVersion = '__SCHEMA_VERSION__';
export type ContentTrust = 'untrusted';
export type SafeAlias = 'coordinator' | 'worker' | 'reviewer' | 'observer';
export type SafeLabel = 'discovery' | 'planning' | 'implementation' | 'validation' | 'review' | 'release' | 'maintenance' | 'blocked';
export type ActivityState = 'idle' | 'queued' | 'working' | 'blocked' | 'completed' | 'cancelled' | 'accepted' | 'rejected';
export type Freshness = 'fresh' | 'stale' | 'unverified' | 'missing' | 'invalid';
export type EventType = 'agent_state' | 'delegation_state' | 'phase_state' | 'checkpoint_observed' | 'help_state' | 'acceptance_state' | 'report_state' | 'source_state';
export type EdgeType = 'delegated_to' | 'communicated_with' | 'assigned_to' | 'works_on' | 'depends_on' | 'blocked_by' | 'supports_gate' | 'reviewed_by';

export interface SafeDisplay {
  labels: string[];
  sourceCount: number;
  containsSecret: boolean;
}

export interface BrowserSafeContext {
  template: 'agent_state' | 'delegation_state' | 'phase_state' | 'checkpoint_observed' | 'help_state' | 'acceptance_state' | 'report_state' | 'source_state';
  data: Record<string, string | number>;
}

export interface BrowserSafeSnapshot {
  schemaVersion: SchemaVersion;
  projectionKind: 'browser-safe-snapshot';
  observedAt: string;
  sequence: number;
  freshness: Freshness;
  contentTrust: ContentTrust;
  grantsAuthority: false;
  safeDisplay: SafeDisplay;
  agents: Array<Record<string, string | number>>;
  goals: Array<Record<string, string | number>>;
  requests: Array<Record<string, string | number>>;
  phases: Array<Record<string, string | number>>;
  tasks: Array<Record<string, string | number>>;
  evidence: Array<Record<string, string | number>>;
  reports: Array<Record<string, string | number>>;
  edges: Array<Record<string, string | number>>;
  events: Array<{ eventType: EventType; sequence: number; occurredAt: string; context: BrowserSafeContext }>;
}

export interface BrowserSafeHistory {
  schemaVersion: SchemaVersion;
  projectionKind: 'browser-safe-history';
  observedAt: string;
  contentTrust: ContentTrust;
  grantsAuthority: false;
  safeDisplay: SafeDisplay;
  detailEvents: Array<{ eventType: EventType; sequence: number; occurredAt: string; context: BrowserSafeContext; redactionState: 'redacted' }>;
  aggregate: Record<string, unknown>;
}

export interface DomainHash { algorithm: 'sha256'; domain: string; digest: string; }

export function validateContract(name: string, value: unknown): unknown;
export function validateBrowserSafeSnapshot(value: unknown): BrowserSafeSnapshot;
export function validateBrowserSafeHistory(value: unknown): BrowserSafeHistory;
export function validateMasterWorkLedger(value: unknown): unknown;
export function validateReportRenderManifest(value: unknown): unknown;
export function validateSafeContext(value: unknown): BrowserSafeContext;
export function renderSafeContext(value: BrowserSafeContext): string;
export function canonicalString(value: unknown): string;
export function domainHash(domain: string, value: unknown): string;
export function validateOpaqueId(value: string, expectedPrefix?: string): string;
export const SCHEMA_VERSION: SchemaVersion;
