'use strict';

// Generated by tools/generate-agent-activity-contracts.js. Do not edit.
// This consumer is deliberately self-contained: it imports only Node's crypto
// primitive for the P07 hash helper and never imports a ToolsEnabled runtime.

const crypto = require('node:crypto');
const CATALOG = __CATALOG_JSON__;
const SCHEMAS = CATALOG.schemas;
const SCHEMA_VERSION = CATALOG.manifest.schemaVersion;
const SCHEMA_BY_ID = Object.create(null);
for (const schema of Object.values(SCHEMAS)) SCHEMA_BY_ID[schema.$id] = schema;
const SAFE_MAX = Number.MAX_SAFE_INTEGER;
const OPAQUE_ID = /^(?:agt|goal|req|phs|tsk|ev|rpt|evt|con|dec|gate|ctx)_[A-Za-z0-9_-]{32}$/;
const DOMAIN = /^[a-z][a-z0-9:._-]{0,127}$/;
const CONTROL_TIMESTAMP = /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/;

function fail(location, message) {
  const error = new Error(location + ': ' + message);
  error.code = 'AGENT_ACTIVITY_CONTRACT_VIOLATION';
  throw error;
}

function isObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value) &&
    (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null);
}

function same(a, b) {
  if (a === b) return true;
  if (!a || !b || typeof a !== 'object' || typeof b !== 'object') return false;
  if (Array.isArray(a) !== Array.isArray(b)) return false;
  if (Array.isArray(a)) return a.length === b.length && a.every((item, index) => same(item, b[index]));
  const keysA = Object.keys(a).sort();
  const keysB = Object.keys(b).sort();
  return keysA.length === keysB.length && keysA.every((key, index) => key === keysB[index] && same(a[key], b[key]));
}

function pointer(root, fragment, location) {
  let value = root;
  if (!fragment) return value;
  if (!fragment.startsWith('/')) fail(location, 'uses an unsupported reference fragment');
  for (const token of fragment.slice(1).split('/')) {
    const key = token.replace(/~1/g, '/').replace(/~0/g, '~');
    if (!value || typeof value !== 'object' || !Object.prototype.hasOwnProperty.call(value, key)) {
      fail(location, 'references a missing schema pointer');
    }
    value = value[key];
  }
  return value;
}

function resolveReference(ref, root, location) {
  const marker = ref.indexOf('#');
  const identifier = marker < 0 ? ref : ref.slice(0, marker);
  const fragment = marker < 0 ? '' : ref.slice(marker + 1);
  const targetRoot = identifier ? SCHEMA_BY_ID[identifier] : root;
  if (!targetRoot) fail(location, 'references an unknown schema ' + ref);
  return { root: targetRoot, schema: pointer(targetRoot, fragment, location) };
}

function typeMatches(type, value) {
  if (type === 'object') return isObject(value);
  if (type === 'array') return Array.isArray(value);
  if (type === 'string') return typeof value === 'string';
  if (type === 'integer') return typeof value === 'number' && Number.isSafeInteger(value);
  if (type === 'number') return typeof value === 'number' && Number.isFinite(value);
  if (type === 'boolean') return typeof value === 'boolean';
  if (type === 'null') return value === null;
  return false;
}

function validateSchema(schema, value, location, root) {
  if (!isObject(schema)) fail(location, 'uses an invalid schema');
  if (schema.$ref) {
    const target = resolveReference(schema.$ref, root, location);
    return validateSchema(target.schema, value, location, target.root);
  }
  if (schema.allOf) {
    for (const child of schema.allOf) validateSchema(child, value, location, root);
  }
  if (schema.oneOf) {
    let matches = 0;
    for (const child of schema.oneOf) {
      try {
        validateSchema(child, value, location, root);
        matches += 1;
      } catch (error) {
        if (error?.code !== 'AGENT_ACTIVITY_CONTRACT_VIOLATION') throw error;
      }
    }
    if (matches !== 1) fail(location, 'must match exactly one closed variant');
  }
  if (Object.prototype.hasOwnProperty.call(schema, 'const') && !same(value, schema.const)) fail(location, 'must equal the required constant');
  if (schema.enum && !schema.enum.some(item => same(value, item))) fail(location, 'must be an allowed enum value');
  const types = schema.type ? (Array.isArray(schema.type) ? schema.type : [schema.type]) : [];
  if (types.length && !types.some(type => typeMatches(type, value))) fail(location, 'has an invalid type');
  const objectShape = types.includes('object') || (!types.length &&
    (schema.properties || schema.required || Object.prototype.hasOwnProperty.call(schema, 'additionalProperties')));
  if (objectShape) {
    if (!isObject(value)) fail(location, 'must be an object');
    const properties = schema.properties || {};
    for (const key of schema.required || []) if (!Object.prototype.hasOwnProperty.call(value, key)) fail(location, 'is missing required property ' + key);
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(value)) if (!Object.prototype.hasOwnProperty.call(properties, key)) fail(location, 'has unknown property ' + key);
    }
    for (const [key, child] of Object.entries(properties)) {
      if (Object.prototype.hasOwnProperty.call(value, key)) validateSchema(child, value[key], location + '.' + key, root);
    }
  }
  const arrayShape = types.includes('array') || (!types.length &&
    (schema.items || schema.minItems !== undefined || schema.maxItems !== undefined || schema.uniqueItems));
  if (arrayShape) {
    if (!Array.isArray(value)) fail(location, 'must be an array');
    if (schema.minItems !== undefined && value.length < schema.minItems) fail(location, 'has too few items');
    if (schema.maxItems !== undefined && value.length > schema.maxItems) fail(location, 'has too many items');
    if (schema.items) value.forEach((item, index) => validateSchema(schema.items, item, location + '[' + index + ']', root));
    if (schema.uniqueItems) {
      const fingerprints = value.map(item => canonicalString(item));
      if (new Set(fingerprints).size !== fingerprints.length) fail(location, 'has duplicate items');
    }
  }
  if (types.includes('string') && typeof value === 'string') {
    if (schema.minLength !== undefined && value.length < schema.minLength) fail(location, 'is too short');
    if (schema.maxLength !== undefined && value.length > schema.maxLength) fail(location, 'is too long');
    if (schema.pattern && !(new RegExp(schema.pattern).test(value))) fail(location, 'does not match its required pattern');
  }
  if ((types.includes('integer') || types.includes('number')) && typeof value === 'number') {
    if (schema.minimum !== undefined && value < schema.minimum) fail(location, 'is below its minimum');
    if (schema.maximum !== undefined && value > schema.maximum) fail(location, 'is above its maximum');
  }
}

function ascii(value, location) {
  if (typeof value !== 'string' || /[^\x20-\x7e]/.test(value)) fail(location, 'must contain printable ASCII only');
  return value;
}

function normalize(value, location = '$') {
  if (value === null || typeof value === 'boolean') return value;
  if (typeof value === 'string') return ascii(value, location);
  if (typeof value === 'number') {
    if (!Number.isSafeInteger(value)) fail(location, 'canonical JSON requires a safe integer');
    return Object.is(value, -0) ? 0 : value;
  }
  if (Array.isArray(value)) return value.map((item, index) => normalize(item, location + '[' + index + ']'));
  if (!isObject(value)) fail(location, 'canonical JSON requires JSON values');
  const result = {};
  for (const key of Object.keys(value).sort()) {
    ascii(key, location + ' key');
    result[key] = normalize(value[key], location + '.' + key);
  }
  return result;
}

function canonicalString(value) {
  return JSON.stringify(normalize(value));
}

function domainHash(domain, value) {
  if (typeof domain !== 'string' || !DOMAIN.test(domain)) fail('domain', 'must be a P07 ASCII domain');
  const frame = Buffer.from('coordinator-platform-hash-v1\0', 'ascii');
  const domainBytes = Buffer.from(domain, 'ascii');
  const payload = Buffer.from(canonicalString(value), 'ascii');
  const length = value => {
    const output = Buffer.alloc(8);
    output.writeBigUInt64BE(BigInt(value));
    return output;
  };
  return crypto.createHash('sha256').update(Buffer.concat([frame, length(domainBytes.length), domainBytes, length(payload.length), payload])).digest('hex');
}

function validateOpaqueId(value, expectedPrefix) {
  if (typeof value !== 'string' || !OPAQUE_ID.test(value)) fail('opaqueId', 'must be a P07-compatible 192-bit opaque ID');
  if (expectedPrefix && !value.startsWith(expectedPrefix + '_')) fail('opaqueId', 'must use the expected lexical prefix');
  return value;
}

function validateControlTimestamp(value, location) {
  if (typeof value !== 'string' || !CONTROL_TIMESTAMP.test(value)) fail(location, 'must be a UTC millisecond ISO-8601 timestamp');
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime()) || parsed.toISOString() !== value) fail(location, 'must be a real UTC timestamp');
}

function visit(value, callback, location = '$') {
  callback(value, location);
  if (Array.isArray(value)) value.forEach((item, index) => visit(item, callback, location + '[' + index + ']'));
  else if (isObject(value)) {
    for (const [key, item] of Object.entries(value)) {
      callback({ key, value: item }, location + '.' + key);
      visit(item, callback, location + '.' + key);
    }
  }
}

function assertControlTimestamps(value) {
  const stack = [{ value, location: '$' }];
  while (stack.length) {
    const current = stack.pop();
    if (Array.isArray(current.value)) current.value.forEach((item, index) => stack.push({ value: item, location: current.location + '[' + index + ']' }));
    else if (isObject(current.value)) {
      for (const [key, item] of Object.entries(current.value)) {
        const next = current.location + '.' + key;
        if (/At$/.test(key)) validateControlTimestamp(item, next);
        stack.push({ value: item, location: next });
      }
    }
  }
}

function asciiCompare(a, b) { return a < b ? -1 : a > b ? 1 : 0; }

function assertEnvelope(value, location) {
  if (!isObject(value) || value.contentTrust !== 'untrusted' || value.grantsAuthority !== false) {
    fail(location, 'must be explicitly untrusted and non-authorizing');
  }
  const display = value.safeDisplay;
  if (!isObject(display) || Object.keys(display).sort().join(',') !== 'containsSecret,labels,sourceCount') {
    fail(location, 'must use the P08 safeDisplay shape only');
  }
  if (!Array.isArray(display.labels) || display.labels.some((item, index, items) => index > 0 && asciiCompare(items[index - 1], item) >= 0)) {
    fail(location + '.safeDisplay.labels', 'must be unique ASCII-ordered provenance labels');
  }
}

const CONTEXT_FOR_EVENT = Object.freeze({
  agent_state: 'agent_state',
  delegation_state: 'delegation_state',
  phase_state: 'phase_state',
  checkpoint_observed: 'checkpoint_observed',
  help_state: 'help_state',
  acceptance_state: 'acceptance_state',
  report_state: 'report_state',
  source_state: 'source_state'
});

function validateSafeContext(value) {
  const common = SCHEMAS.common;
  validateSchema(common.$defs.contextTemplate, value, 'context', common);
  return value;
}

function assertEventContext(event, location) {
  validateSafeContext(event.context);
  if (CONTEXT_FOR_EVENT[event.eventType] !== event.context.template) {
    fail(location + '.context', 'template must exactly match the event type');
  }
}

function unsafeString(value) {
  return /TOOLSENABLED_CANARY_|-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----|vault:\/\/|\b(?:Bearer|Basic)\s+[A-Za-z0-9._~+\/=:-]{12,}|\b(?:sk_(?:live|test|prod)_[A-Za-z0-9_-]{12,}|AIza[0-9A-Za-z_-]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{20,}|AKIA[0-9A-Z]{16}|ya29\.[A-Za-z0-9._-]{12,})|\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.(?:invalid|com|org|net)\b|\b\d{3}[- ]?\d{2}[- ]?\d{4}\b|\b(?:ignore (?:all )?(?:previous|prior)|system message|tool result)\b/i.test(value);
}

const BROWSER_FORBIDDEN_KEYS = new Set([
  'agentId', 'goalId', 'requestId', 'phaseId', 'taskId', 'evidenceId', 'reportId', 'eventId', 'edgeId', 'entityId',
  'contentHash', 'eventHash', 'ledgerHash', 'htmlHash', 'pdfHash', 'path', 'paths', 'normalizedPaths',
  'objective', 'prompt', 'mission', 'checkpointText', 'checkpointResult', 'helpText', 'helpResult',
  'toolArgs', 'toolResult', 'memory', 'audit', 'vault', 'secretValue', 'response', 'reasoning', 'chainOfThought'
]);

function assertBrowserSafe(value, location = '$') {
  if (typeof value === 'string' && unsafeString(value)) fail(location, 'contains unsafe sensitive, PII, or instruction-like content');
  if (Array.isArray(value)) return value.forEach((item, index) => assertBrowserSafe(item, location + '[' + index + ']'));
  if (!isObject(value)) return;
  for (const [key, item] of Object.entries(value)) {
    if (BROWSER_FORBIDDEN_KEYS.has(key) || /(?:Id|Ids|Hash|Path|Paths)$/.test(key)) {
      fail(location + '.' + key, 'browser-safe payload must not expose raw identifiers, hashes, or paths');
    }
    assertBrowserSafe(item, location + '.' + key);
  }
}

const EDGE_PAIRS = Object.freeze({
  delegated_to: [['agent', 'agent']],
  communicated_with: [['agent', 'agent']],
  assigned_to: [['task', 'agent'], ['phase', 'agent'], ['request', 'agent']],
  works_on: [['agent', 'goal'], ['agent', 'request'], ['agent', 'phase'], ['agent', 'task']],
  depends_on: [['phase', 'phase'], ['phase', 'task'], ['task', 'phase'], ['task', 'task']],
  blocked_by: [['request', 'gate'], ['phase', 'gate'], ['phase', 'phase'], ['phase', 'task'], ['task', 'gate'], ['task', 'phase'], ['task', 'task']],
  supports_gate: [['evidence', 'gate'], ['task', 'gate'], ['report', 'gate']],
  reviewed_by: [['report', 'agent'], ['task', 'agent'], ['phase', 'agent']]
});

function assertEdge(edge) {
  validateOpaqueId(edge.edgeId, 'evt');
  const pair = [edge.from.entityType, edge.to.entityType];
  if (!EDGE_PAIRS[edge.edgeType]?.some(candidate => candidate[0] === pair[0] && candidate[1] === pair[1])) {
    fail('edge', 'uses an invalid typed edge direction');
  }
}

function assertEvent(event) {
  validateOpaqueId(event.eventId, 'evt');
  validateOpaqueId(event.owner.entityId);
  assertEventContext(event, 'event');
  if (event.eventHash.domain !== 'agent-activity:event:1.0.0') fail('event.eventHash', 'must use the event P07 hash domain');
}

function assertInternalId(name, value) {
  const fields = {
    agent: ['agentId', 'agt'], goal: ['goalId', 'goal'], request: ['requestId', 'req'], phase: ['phaseId', 'phs'],
    task: ['taskId', 'tsk'], evidence: ['evidenceId', 'ev'], report: ['reportId', 'rpt']
  };
  if (fields[name]) validateOpaqueId(value[fields[name][0]], fields[name][1]);
}

function assertReportManifest(value) {
  const expected = {
    ledgerHash: 'master-work-ledger:2.0.0',
    htmlHash: 'agent-activity:report-html:1.0.0',
    pdfHash: 'agent-activity:report-pdf:1.0.0'
  };
  for (const [field, domain] of Object.entries(expected)) {
    if (value[field].domain !== domain) fail('report-render-manifest.' + field, 'uses an unexpected P07 hash domain');
  }
}

function collect(records, field, prefix, location) {
  const values = new Set();
  for (const record of records) {
    validateOpaqueId(record[field], prefix);
    if (values.has(record[field])) fail(location, 'contains a duplicate stable ID');
    values.add(record[field]);
  }
  return values;
}

function assertReferences(ids, known, location) {
  for (const id of ids) if (!known.has(id)) fail(location, 'references an ID outside this ledger');
}

function validateMasterWorkLedger(value) {
  validateSchema(SCHEMAS['master-work-ledger'], value, 'master-work-ledger', SCHEMAS['master-work-ledger']);
  assertEnvelope(value, 'master-work-ledger');
  assertControlTimestamps(value);
  const goals = collect(value.goals, 'goalId', 'goal', 'master-work-ledger.goals');
  const requests = collect(value.requests, 'requestId', 'req', 'master-work-ledger.requests');
  const constraints = collect(value.constraints, 'constraintId', 'con', 'master-work-ledger.constraints');
  const decisions = collect(value.decisions, 'decisionId', 'dec', 'master-work-ledger.decisions');
  const gates = collect(value.gates, 'gateId', 'gate', 'master-work-ledger.gates');
  const phases = collect(value.phases, 'phaseId', 'phs', 'master-work-ledger.phases');
  validateOpaqueId(value.masterLink.missionId, 'ctx');
  validateOpaqueId(value.masterLink.requestId, 'req');
  validateOpaqueId(value.masterLink.phaseId, 'phs');
  if (value.masterLink.observedLedgerRevision > value.ledgerRevision) fail('master-work-ledger.masterLink', 'cannot observe a future ledger revision');
  assertReferences([value.masterLink.requestId], requests, 'master-work-ledger.masterLink.requestId');
  assertReferences([value.masterLink.phaseId], phases, 'master-work-ledger.masterLink.phaseId');
  assertReferences(value.masterLink.gateIds, gates, 'master-work-ledger.masterLink.gateIds');
  for (const item of value.goals) {
    assertReferences(item.requestIds, requests, 'master-work-ledger.goals.requestIds');
    assertReferences(item.constraintIds, constraints, 'master-work-ledger.goals.constraintIds');
    assertReferences(item.decisionIds, decisions, 'master-work-ledger.goals.decisionIds');
    assertReferences(item.gateIds, gates, 'master-work-ledger.goals.gateIds');
    assertReferences(item.phaseIds, phases, 'master-work-ledger.goals.phaseIds');
  }
  for (const item of value.requests) {
    validateOpaqueId(item.goalId, 'goal');
    assertReferences([item.goalId], goals, 'master-work-ledger.requests.goalId');
    assertReferences(item.gateIds, gates, 'master-work-ledger.requests.gateIds');
    assertReferences(item.plannedPhaseIds, phases, 'master-work-ledger.requests.plannedPhaseIds');
  }
  for (const item of value.constraints) {
    assertReferences(item.goalIds, goals, 'master-work-ledger.constraints.goalIds');
    assertReferences(item.phaseIds, phases, 'master-work-ledger.constraints.phaseIds');
  }
  for (const item of value.decisions) {
    assertReferences(item.goalIds, goals, 'master-work-ledger.decisions.goalIds');
    assertReferences(item.gateIds, gates, 'master-work-ledger.decisions.gateIds');
  }
  for (const item of value.gates) assertReferences(item.phaseIds, phases, 'master-work-ledger.gates.phaseIds');
  for (const item of value.phases) {
    validateOpaqueId(item.goalId, 'goal');
    assertReferences([item.goalId], goals, 'master-work-ledger.phases.goalId');
    assertReferences(item.requestIds, requests, 'master-work-ledger.phases.requestIds');
    assertReferences(item.dependsOnPhaseIds, phases, 'master-work-ledger.phases.dependsOnPhaseIds');
    assertReferences(item.gateIds, gates, 'master-work-ledger.phases.gateIds');
  }
  return value;
}

function validateContract(name, value) {
  if (name === 'master-work-ledger') return validateMasterWorkLedger(value);
  const schema = SCHEMAS[name];
  if (!schema || name === 'common') fail('contract', 'is not a concrete contract');
  validateSchema(schema, value, name, schema);
  assertEnvelope(value, name);
  assertControlTimestamps(value);
  assertInternalId(name, value);
  if (name === 'edge') assertEdge(value);
  if (name === 'event') assertEvent(value);
  if (name === 'report-render-manifest') assertReportManifest(value);
  if (name === 'browser-event') {
    assertBrowserSafe(value);
    assertEventContext(value, 'browser-event');
  }
  if (name === 'snapshot') {
    assertBrowserSafe(value);
    for (const event of value.events) assertEventContext(event, 'snapshot.events');
  }
  if (name === 'history') {
    assertBrowserSafe(value);
    for (const event of value.detailEvents) assertEventContext(event, 'history.detailEvents');
  }
  return value;
}

function validateBrowserSafeSnapshot(value) { return validateContract('snapshot', value); }
function validateBrowserSafeHistory(value) { return validateContract('history', value); }
function validateReportRenderManifest(value) { return validateContract('report-render-manifest', value); }

function renderSafeContext(value) {
  validateSafeContext(value);
  const data = value.data;
  if (value.template === 'agent_state') return data.agentAlias + ' is ' + data.state + '.';
  if (value.template === 'delegation_state') return 'Delegation to ' + data.agentAlias + ' is ' + data.state + '.';
  if (value.template === 'phase_state') return data.phaseLabel + ' is ' + data.state + ' at ' + data.progressPercent + '%.';
  if (value.template === 'checkpoint_observed') return data.checkpointCount + ' checkpoint(s) observed.';
  if (value.template === 'help_state') return 'Help state is ' + data.state + '.';
  if (value.template === 'acceptance_state') return 'Acceptance is ' + data.acceptance + '.';
  if (value.template === 'report_state') return 'Report is ' + data.state + ' (' + data.freshness + ').';
  return data.evidenceCount + ' ' + data.evidenceKind + ' source(s) are ' + data.freshness + '.';
}

module.exports = {
  SCHEMA_VERSION,
  canonicalString,
  domainHash,
  renderSafeContext,
  validateBrowserSafeHistory,
  validateBrowserSafeSnapshot,
  validateContract,
  validateMasterWorkLedger,
  validateOpaqueId,
  validateReportRenderManifest,
  validateSafeContext
};
