# Generated by tools/generate-agent-activity-contracts.js. Do not edit.
# Standard-library-only consumer; it has no ToolsEnabled runtime dependency.

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime
from typing import Any

CATALOG: dict[str, Any] = json.loads(r'''__CATALOG_JSON__''')
SCHEMAS: dict[str, Any] = CATALOG['schemas']
SCHEMA_VERSION: str = CATALOG['manifest']['schemaVersion']
SCHEMA_BY_ID: dict[str, dict[str, Any]] = {schema['$id']: schema for schema in SCHEMAS.values()}
SAFE_MAX = 9007199254740991
OPAQUE_ID = re.compile(r'^(?:agt|goal|req|phs|tsk|ev|rpt|evt|con|dec|gate|ctx)_[A-Za-z0-9_-]{32}$')
DOMAIN = re.compile(r'^[a-z][a-z0-9:._-]{0,127}$')
CONTROL_TIMESTAMP = re.compile(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$')


def _fail(location: str, message: str) -> None:
    raise ValueError(f'{location}: {message}')


def _is_object(value: Any) -> bool:
    return isinstance(value, dict)


def _same(left: Any, right: Any) -> bool:
    if type(left) is not type(right):
        return False
    if isinstance(left, list):
        return len(left) == len(right) and all(_same(item, right[index]) for index, item in enumerate(left))
    if isinstance(left, dict):
        return set(left) == set(right) and all(_same(left[key], right[key]) for key in left)
    return left == right


def _pointer(root: dict[str, Any], fragment: str, location: str) -> Any:
    value: Any = root
    if not fragment:
        return value
    if not fragment.startswith('/'):
        _fail(location, 'uses an unsupported reference fragment')
    for token in fragment[1:].split('/'):
        key = token.replace('~1', '/').replace('~0', '~')
        if not isinstance(value, dict) or key not in value:
            _fail(location, 'references a missing schema pointer')
        value = value[key]
    return value


def _resolve(ref: str, root: dict[str, Any], location: str) -> tuple[dict[str, Any], dict[str, Any]]:
    identifier, marker, fragment = ref.partition('#')
    target_root = SCHEMA_BY_ID.get(identifier) if identifier else root
    if target_root is None:
        _fail(location, 'references an unknown schema ' + ref)
    return target_root, _pointer(target_root, fragment if marker else '', location)


def _type_matches(kind: str, value: Any) -> bool:
    if kind == 'object':
        return _is_object(value)
    if kind == 'array':
        return isinstance(value, list)
    if kind == 'string':
        return isinstance(value, str)
    if kind == 'integer':
        return type(value) is int and abs(value) <= SAFE_MAX
    if kind == 'number':
        return type(value) in (int, float) and abs(value) <= SAFE_MAX
    if kind == 'boolean':
        return type(value) is bool
    if kind == 'null':
        return value is None
    return False


def _validate(schema: dict[str, Any], value: Any, location: str, root: dict[str, Any]) -> None:
    if not _is_object(schema):
        _fail(location, 'uses an invalid schema')
    if '$ref' in schema:
        target_root, target = _resolve(schema['$ref'], root, location)
        _validate(target, value, location, target_root)
        return
    for child in schema.get('allOf', []):
        _validate(child, value, location, root)
    if 'oneOf' in schema:
        matches = 0
        for child in schema['oneOf']:
            try:
                _validate(child, value, location, root)
                matches += 1
            except ValueError:
                pass
        if matches != 1:
            _fail(location, 'must match exactly one closed variant')
    if 'const' in schema and not _same(value, schema['const']):
        _fail(location, 'must equal the required constant')
    if 'enum' in schema and not any(_same(value, item) for item in schema['enum']):
        _fail(location, 'must be an allowed enum value')
    declared = schema.get('type')
    kinds = declared if isinstance(declared, list) else ([declared] if declared else [])
    if kinds and not any(_type_matches(kind, value) for kind in kinds):
        _fail(location, 'has an invalid type')
    object_shape = 'object' in kinds or (not kinds and any(key in schema for key in ('properties', 'required', 'additionalProperties')))
    if object_shape:
        if not _is_object(value):
            _fail(location, 'must be an object')
        properties = schema.get('properties', {})
        for key in schema.get('required', []):
            if key not in value:
                _fail(location, 'is missing required property ' + key)
        if schema.get('additionalProperties') is False:
            for key in value:
                if key not in properties:
                    _fail(location, 'has unknown property ' + key)
        for key, child in properties.items():
            if key in value:
                _validate(child, value[key], location + '.' + key, root)
    array_shape = 'array' in kinds or (not kinds and any(key in schema for key in ('items', 'minItems', 'maxItems', 'uniqueItems')))
    if array_shape:
        if not isinstance(value, list):
            _fail(location, 'must be an array')
        if 'minItems' in schema and len(value) < schema['minItems']:
            _fail(location, 'has too few items')
        if 'maxItems' in schema and len(value) > schema['maxItems']:
            _fail(location, 'has too many items')
        if 'items' in schema:
            for index, item in enumerate(value):
                _validate(schema['items'], item, f'{location}[{index}]', root)
        if schema.get('uniqueItems'):
            fingerprints = [canonical_string(item) for item in value]
            if len(set(fingerprints)) != len(fingerprints):
                _fail(location, 'has duplicate items')
    string_shape = 'string' in kinds
    if string_shape:
        if not isinstance(value, str):
            _fail(location, 'must be a string')
        if 'minLength' in schema and len(value) < schema['minLength']:
            _fail(location, 'is too short')
        if 'maxLength' in schema and len(value) > schema['maxLength']:
            _fail(location, 'is too long')
        if 'pattern' in schema and re.search(schema['pattern'], value) is None:
            _fail(location, 'does not match its required pattern')
    if ('integer' in kinds or 'number' in kinds) and type(value) in (int, float):
        if 'minimum' in schema and value < schema['minimum']:
            _fail(location, 'is below its minimum')
        if 'maximum' in schema and value > schema['maximum']:
            _fail(location, 'is above its maximum')


def _ascii(value: str, location: str) -> str:
    if not isinstance(value, str) or any(ord(char) < 32 or ord(char) > 126 for char in value):
        _fail(location, 'must contain printable ASCII only')
    return value


def _normalize(value: Any, location: str = '$') -> Any:
    if value is None or type(value) is bool:
        return value
    if isinstance(value, str):
        return _ascii(value, location)
    if type(value) is int:
        if abs(value) > SAFE_MAX:
            _fail(location, 'canonical JSON requires a safe integer')
        return value
    if type(value) is float:
        _fail(location, 'canonical JSON requires a safe integer')
    if isinstance(value, list):
        return [_normalize(item, f'{location}[{index}]') for index, item in enumerate(value)]
    if not _is_object(value):
        _fail(location, 'canonical JSON requires JSON values')
    output: dict[str, Any] = {}
    for key in sorted(value):
        _ascii(key, location + ' key')
        output[key] = _normalize(value[key], location + '.' + key)
    return output


def canonical_string(value: Any) -> str:
    return json.dumps(_normalize(value), ensure_ascii=True, sort_keys=True, separators=(',', ':'), allow_nan=False)


def domain_hash(domain: str, value: Any) -> str:
    if not isinstance(domain, str) or DOMAIN.fullmatch(domain) is None:
        _fail('domain', 'must be a P07 ASCII domain')
    domain_bytes = domain.encode('ascii')
    payload = canonical_string(value).encode('ascii')
    frame = b'coordinator-platform-hash-v1\x00'
    return hashlib.sha256(frame + len(domain_bytes).to_bytes(8, 'big') + domain_bytes + len(payload).to_bytes(8, 'big') + payload).hexdigest()


def validate_opaque_id(value: str, expected_prefix: str | None = None) -> str:
    if not isinstance(value, str) or OPAQUE_ID.fullmatch(value) is None:
        _fail('opaqueId', 'must be a P07-compatible 192-bit opaque ID')
    if expected_prefix is not None and not value.startswith(expected_prefix + '_'):
        _fail('opaqueId', 'must use the expected lexical prefix')
    return value


def _validate_control_timestamp(value: Any, location: str) -> None:
    if not isinstance(value, str) or CONTROL_TIMESTAMP.fullmatch(value) is None:
        _fail(location, 'must be a UTC millisecond ISO-8601 timestamp')
    try:
        parsed = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%fZ')
    except ValueError:
        _fail(location, 'must be a real UTC timestamp')
    normalized = parsed.strftime('%Y-%m-%dT%H:%M:%S.') + f'{parsed.microsecond // 1000:03d}Z'
    if normalized != value:
        _fail(location, 'must be a real UTC timestamp')


def _assert_control_timestamps(value: Any, location: str = '$') -> None:
    if isinstance(value, list):
        for index, item in enumerate(value):
            _assert_control_timestamps(item, f'{location}[{index}]')
    elif _is_object(value):
        for key, item in value.items():
            next_location = location + '.' + key
            if key.endswith('At'):
                _validate_control_timestamp(item, next_location)
            _assert_control_timestamps(item, next_location)


def _assert_envelope(value: Any, location: str) -> None:
    if not _is_object(value) or value.get('contentTrust') != 'untrusted' or value.get('grantsAuthority') is not False:
        _fail(location, 'must be explicitly untrusted and non-authorizing')
    display = value.get('safeDisplay')
    if not _is_object(display) or sorted(display) != ['containsSecret', 'labels', 'sourceCount']:
        _fail(location, 'must use the P08 safeDisplay shape only')
    labels = display.get('labels')
    if not isinstance(labels, list) or labels != sorted(set(labels)):
        _fail(location + '.safeDisplay.labels', 'must be unique ASCII-ordered provenance labels')


CONTEXT_FOR_EVENT = {
    'agent_state': 'agent_state',
    'delegation_state': 'delegation_state',
    'phase_state': 'phase_state',
    'checkpoint_observed': 'checkpoint_observed',
    'help_state': 'help_state',
    'acceptance_state': 'acceptance_state',
    'report_state': 'report_state',
    'source_state': 'source_state'
}


def validate_safe_context(value: Any) -> Any:
    common = SCHEMAS['common']
    _validate(common['$defs']['contextTemplate'], value, 'context', common)
    return value


def _assert_event_context(event: dict[str, Any], location: str) -> None:
    validate_safe_context(event['context'])
    if CONTEXT_FOR_EVENT.get(event['eventType']) != event['context']['template']:
        _fail(location + '.context', 'template must exactly match the event type')


UNSAFE_STRING = re.compile(
    r'TOOLSENABLED_CANARY_|-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----|vault://|\b(?:Bearer|Basic)\s+[A-Za-z0-9._~+/=:-]{12,}|'
    r'\b(?:sk_(?:live|test|prod)_[A-Za-z0-9_-]{12,}|AIza[0-9A-Za-z_-]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{20,}|AKIA[0-9A-Z]{16}|ya29\.[A-Za-z0-9._-]{12,})|'
    r'\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.(?:invalid|com|org|net)\b|\b\d{3}[- ]?\d{2}[- ]?\d{4}\b|'
    r'\b(?:ignore (?:all )?(?:previous|prior)|system message|tool result)\b', re.IGNORECASE)
BROWSER_FORBIDDEN_KEYS = {
    'agentId', 'goalId', 'requestId', 'phaseId', 'taskId', 'evidenceId', 'reportId', 'eventId', 'edgeId', 'entityId',
    'contentHash', 'eventHash', 'ledgerHash', 'htmlHash', 'pdfHash', 'path', 'paths', 'normalizedPaths',
    'objective', 'prompt', 'mission', 'checkpointText', 'checkpointResult', 'helpText', 'helpResult',
    'toolArgs', 'toolResult', 'memory', 'audit', 'vault', 'secretValue', 'response', 'reasoning', 'chainOfThought'
}


def _assert_browser_safe(value: Any, location: str = '$') -> None:
    if isinstance(value, str) and UNSAFE_STRING.search(value):
        _fail(location, 'contains unsafe sensitive, PII, or instruction-like content')
    if isinstance(value, list):
        for index, item in enumerate(value):
            _assert_browser_safe(item, f'{location}[{index}]')
    elif _is_object(value):
        for key, item in value.items():
            if key in BROWSER_FORBIDDEN_KEYS or re.search(r'(?:Id|Ids|Hash|Path|Paths)$', key):
                _fail(location + '.' + key, 'browser-safe payload must not expose raw identifiers, hashes, or paths')
            _assert_browser_safe(item, location + '.' + key)


EDGE_PAIRS = {
    'delegated_to': {('agent', 'agent')},
    'communicated_with': {('agent', 'agent')},
    'assigned_to': {('task', 'agent'), ('phase', 'agent'), ('request', 'agent')},
    'works_on': {('agent', 'goal'), ('agent', 'request'), ('agent', 'phase'), ('agent', 'task')},
    'depends_on': {('phase', 'phase'), ('phase', 'task'), ('task', 'phase'), ('task', 'task')},
    'blocked_by': {('request', 'gate'), ('phase', 'gate'), ('phase', 'phase'), ('phase', 'task'), ('task', 'gate'), ('task', 'phase'), ('task', 'task')},
    'supports_gate': {('evidence', 'gate'), ('task', 'gate'), ('report', 'gate')},
    'reviewed_by': {('report', 'agent'), ('task', 'agent'), ('phase', 'agent')}
}


def _assert_edge(edge: dict[str, Any]) -> None:
    validate_opaque_id(edge['edgeId'], 'evt')
    if (edge['from']['entityType'], edge['to']['entityType']) not in EDGE_PAIRS[edge['edgeType']]:
        _fail('edge', 'uses an invalid typed edge direction')


def _assert_event(event: dict[str, Any]) -> None:
    validate_opaque_id(event['eventId'], 'evt')
    validate_opaque_id(event['owner']['entityId'])
    _assert_event_context(event, 'event')
    if event['eventHash']['domain'] != 'agent-activity:event:1.0.0':
        _fail('event.eventHash', 'must use the event P07 hash domain')


def _assert_internal_id(name: str, value: dict[str, Any]) -> None:
    fields = {
        'agent': ('agentId', 'agt'), 'goal': ('goalId', 'goal'), 'request': ('requestId', 'req'),
        'phase': ('phaseId', 'phs'), 'task': ('taskId', 'tsk'), 'evidence': ('evidenceId', 'ev'), 'report': ('reportId', 'rpt')
    }
    if name in fields:
        field, prefix = fields[name]
        validate_opaque_id(value[field], prefix)


def _assert_report_manifest(value: dict[str, Any]) -> None:
    expected = {
        'ledgerHash': 'master-work-ledger:2.0.0',
        'htmlHash': 'agent-activity:report-html:1.0.0',
        'pdfHash': 'agent-activity:report-pdf:1.0.0'
    }
    for field, domain in expected.items():
        if value[field]['domain'] != domain:
            _fail('report-render-manifest.' + field, 'uses an unexpected P07 hash domain')


def _collect(records: list[dict[str, Any]], field: str, prefix: str, location: str) -> set[str]:
    values: set[str] = set()
    for record in records:
        validate_opaque_id(record[field], prefix)
        if record[field] in values:
            _fail(location, 'contains a duplicate stable ID')
        values.add(record[field])
    return values


def _assert_references(ids: list[str], known: set[str], location: str) -> None:
    for value in ids:
        if value not in known:
            _fail(location, 'references an ID outside this ledger')


def validate_master_work_ledger(value: Any) -> Any:
    schema = SCHEMAS['master-work-ledger']
    _validate(schema, value, 'master-work-ledger', schema)
    _assert_envelope(value, 'master-work-ledger')
    _assert_control_timestamps(value)
    goals = _collect(value['goals'], 'goalId', 'goal', 'master-work-ledger.goals')
    requests = _collect(value['requests'], 'requestId', 'req', 'master-work-ledger.requests')
    constraints = _collect(value['constraints'], 'constraintId', 'con', 'master-work-ledger.constraints')
    decisions = _collect(value['decisions'], 'decisionId', 'dec', 'master-work-ledger.decisions')
    gates = _collect(value['gates'], 'gateId', 'gate', 'master-work-ledger.gates')
    phases = _collect(value['phases'], 'phaseId', 'phs', 'master-work-ledger.phases')
    link = value['masterLink']
    validate_opaque_id(link['missionId'], 'ctx')
    validate_opaque_id(link['requestId'], 'req')
    validate_opaque_id(link['phaseId'], 'phs')
    if link['observedLedgerRevision'] > value['ledgerRevision']:
        _fail('master-work-ledger.masterLink', 'cannot observe a future ledger revision')
    _assert_references([link['requestId']], requests, 'master-work-ledger.masterLink.requestId')
    _assert_references([link['phaseId']], phases, 'master-work-ledger.masterLink.phaseId')
    _assert_references(link['gateIds'], gates, 'master-work-ledger.masterLink.gateIds')
    for item in value['goals']:
        _assert_references(item['requestIds'], requests, 'master-work-ledger.goals.requestIds')
        _assert_references(item['constraintIds'], constraints, 'master-work-ledger.goals.constraintIds')
        _assert_references(item['decisionIds'], decisions, 'master-work-ledger.goals.decisionIds')
        _assert_references(item['gateIds'], gates, 'master-work-ledger.goals.gateIds')
        _assert_references(item['phaseIds'], phases, 'master-work-ledger.goals.phaseIds')
    for item in value['requests']:
        validate_opaque_id(item['goalId'], 'goal')
        _assert_references([item['goalId']], goals, 'master-work-ledger.requests.goalId')
        _assert_references(item['gateIds'], gates, 'master-work-ledger.requests.gateIds')
        _assert_references(item['plannedPhaseIds'], phases, 'master-work-ledger.requests.plannedPhaseIds')
    for item in value['constraints']:
        _assert_references(item['goalIds'], goals, 'master-work-ledger.constraints.goalIds')
        _assert_references(item['phaseIds'], phases, 'master-work-ledger.constraints.phaseIds')
    for item in value['decisions']:
        _assert_references(item['goalIds'], goals, 'master-work-ledger.decisions.goalIds')
        _assert_references(item['gateIds'], gates, 'master-work-ledger.decisions.gateIds')
    for item in value['gates']:
        _assert_references(item['phaseIds'], phases, 'master-work-ledger.gates.phaseIds')
    for item in value['phases']:
        validate_opaque_id(item['goalId'], 'goal')
        _assert_references([item['goalId']], goals, 'master-work-ledger.phases.goalId')
        _assert_references(item['requestIds'], requests, 'master-work-ledger.phases.requestIds')
        _assert_references(item['dependsOnPhaseIds'], phases, 'master-work-ledger.phases.dependsOnPhaseIds')
        _assert_references(item['gateIds'], gates, 'master-work-ledger.phases.gateIds')
    return value


def validate_contract(name: str, value: Any) -> Any:
    if name == 'master-work-ledger':
        return validate_master_work_ledger(value)
    if name not in SCHEMAS or name == 'common':
        _fail('contract', 'is not a concrete contract')
    schema = SCHEMAS[name]
    _validate(schema, value, name, schema)
    _assert_envelope(value, name)
    _assert_control_timestamps(value)
    _assert_internal_id(name, value)
    if name == 'edge':
        _assert_edge(value)
    if name == 'event':
        _assert_event(value)
    if name == 'report-render-manifest':
        _assert_report_manifest(value)
    if name == 'browser-event':
        _assert_browser_safe(value)
        _assert_event_context(value, 'browser-event')
    if name == 'snapshot':
        _assert_browser_safe(value)
        for event in value['events']:
            _assert_event_context(event, 'snapshot.events')
    if name == 'history':
        _assert_browser_safe(value)
        for event in value['detailEvents']:
            _assert_event_context(event, 'history.detailEvents')
    return value


def validate_browser_safe_snapshot(value: Any) -> Any:
    return validate_contract('snapshot', value)


def validate_browser_safe_history(value: Any) -> Any:
    return validate_contract('history', value)


def validate_report_render_manifest(value: Any) -> Any:
    return validate_contract('report-render-manifest', value)


def render_safe_context(value: Any) -> str:
    validate_safe_context(value)
    data = value['data']
    template = value['template']
    if template == 'agent_state':
        return f"{data['agentAlias']} is {data['state']}."
    if template == 'delegation_state':
        return f"Delegation to {data['agentAlias']} is {data['state']}."
    if template == 'phase_state':
        return f"{data['phaseLabel']} is {data['state']} at {data['progressPercent']}%."
    if template == 'checkpoint_observed':
        return f"{data['checkpointCount']} checkpoint(s) observed."
    if template == 'help_state':
        return f"Help state is {data['state']}."
    if template == 'acceptance_state':
        return f"Acceptance is {data['acceptance']}."
    if template == 'report_state':
        return f"Report is {data['state']} ({data['freshness']})."
    return f"{data['evidenceCount']} {data['evidenceKind']} source(s) are {data['freshness']}."


__all__ = [
    'SCHEMA_VERSION', 'canonical_string', 'domain_hash', 'render_safe_context',
    'validate_browser_safe_history', 'validate_browser_safe_snapshot', 'validate_contract',
    'validate_master_work_ledger', 'validate_opaque_id', 'validate_report_render_manifest', 'validate_safe_context'
]
