#!/usr/bin/env python3
"""Write a DeepSeek Harness (DSH) overlay that connects ToolsEnabled Fleet as an MCP server.

Run it inside the OpenShell sandbox where Fleet is installed. It copies Fleet's
existing MCP registration (made by `toolsenabled setup`) from the Codex or
Claude Code configuration into a DSH Cordis overlay that uses DSH's built-in
`@deepseek-ai/dsh-mcp-client` plugin. It reads only Fleet's own `toolsenabled`
entry and changes no other file.

    python3 fleet-dsh-overlay.py [--from codex|claude] [--output PATH] [--cwd DIR] [--force]

Then start DSH with the overlay, for example:

    dsh web --patch ~/toolsenabled-fleet.cordis.yml
"""

import argparse
import json
import os
import sys
from pathlib import Path

SERVER = 'toolsenabled'
# Fleet records which agent (codex, claude) acted; DSH is not one of them yet,
# so its actions are recorded without an agent label.
DROP = {'TOOLSENABLED_AGENT_ACTOR'}


def from_codex():
    try:
        import tomllib
    except ImportError:
        raise SystemExit('Reading the Codex registration needs Python 3.11+; use --from claude.')
    home = Path(os.environ.get('CODEX_HOME') or Path.home() / '.codex')
    path = home / 'config.toml'
    if not path.is_file():
        return None
    entry = tomllib.loads(path.read_text()).get('mcp_servers', {}).get(SERVER)
    return entry and {'command': entry.get('command'), 'args': entry.get('args', []), 'env': entry.get('env', {})}


def from_claude():
    base = os.environ.get('CLAUDE_CONFIG_DIR')
    path = Path(base) / '.claude.json' if base else Path.home() / '.claude.json'
    if not path.is_file():
        return None
    entry = json.loads(path.read_text()).get('mcpServers', {}).get(SERVER)
    return entry and {'command': entry.get('command'), 'args': entry.get('args', []), 'env': entry.get('env', {})}


def check(entry):
    command, args, env = entry['command'], entry['args'], entry['env']
    ok = (isinstance(command, str) and command.startswith('/')
          and isinstance(args, list) and len(args) == 1 and isinstance(args[0], str)
          and args[0].startswith('/') and args[0].endswith('/mcp-server.js')
          and isinstance(env, dict)
          and all(isinstance(k, str) and isinstance(v, str) and '\n' not in v for k, v in env.items()))
    if not ok:
        raise SystemExit('The toolsenabled registration does not look like a Fleet setup; nothing was written.')


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--from', dest='source', choices=('codex', 'claude'))
    parser.add_argument('--output', type=Path, default=Path.home() / 'toolsenabled-fleet.cordis.yml')
    parser.add_argument('--cwd', default=None, help='working folder for the Fleet server (default: the folder DSH runs in)')
    parser.add_argument('--force', action='store_true', help='replace an existing output file')
    args = parser.parse_args()

    readers = {'codex': from_codex, 'claude': from_claude}
    order = [args.source] if args.source else ['codex', 'claude']
    entry = next((e for e in (readers[name]() for name in order) if e), None)
    if not entry:
        raise SystemExit('No Fleet registration found. Install Fleet and run `toolsenabled setup` first.')
    check(entry)
    if args.output.exists() and not args.force:
        raise SystemExit(f'{args.output} exists; pass --force to replace it.')

    q = json.dumps
    env = {k: v for k, v in entry['env'].items() if k not in DROP}
    lines = ['# ToolsEnabled Fleet as an MCP server for DeepSeek Harness.',
             '# Generated by fleet-dsh-overlay.py from your Fleet setup. Re-run it after a Fleet upgrade.',
             '- insert:',
             '    - id: mcp-toolsenabled-fleet',
             "      name: '@deepseek-ai/dsh-mcp-client'",
             '      config:',
             f'        serverName: {SERVER}',
             '        transport: stdio',
             f"        command: {q(entry['command'])}",
             f"        args: [{q(entry['args'][0])}]",
             '        env:']
    lines += [f'          {k}: {q(v)}' for k, v in sorted(env.items())]
    lines.append(f'        cwd: {q(args.cwd)}' if args.cwd else '        cwd: !!js process.cwd()')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(args.output, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, 'w') as stream:
        stream.write('\n'.join(lines) + '\n')
    print(f'Wrote {args.output}')
    print(f'Start DeepSeek Harness with it:  dsh web --patch {args.output}')
    print('Fleet tools then appear in DSH as mcp__toolsenabled__<tool>.')


if __name__ == '__main__':
    sys.exit(main())
